# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        descriptions: input update to version command. 'major' 'minor' 'patch' 'premajor' 'preminor' 'prepatch' 'prerelease'
        required: true
        default: 'prerelease'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm version ${{ github.event.inputs.version }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --tags
