# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        descriptions: input update to version command. 'major' 'minor' 'patch' 'premajor' 'preminor' 'prepatch' 'prerelease'
        required: true
        default: 'prerelease'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm ci
          npm run build

      - name: Setup git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git remote show origin
          npm version ${{ github.event.inputs.version }}

          git push --tags origin main

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
