name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - name: Publish to npm
        run: |
          npm run publish 2>&1 | tee publish.log
          # Check if the error is about package already being published
          if grep -q "You cannot publish over the previously published versions" publish.log; then
            echo "::warning::Package version already published, skipping..."
            exit 0
          fi
          # Check the actual exit code of the publish command
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "::error::Publish failed with unexpected error"
            exit 1
          fi
          echo "::notice::Package published successfully"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
